# Generated by Django 5.0.6 on 2024-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
