# Generated by Django 5.0.6 on 2024-05-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note_api', '0002_alter_note_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='date',
        ),
    ]
